name: Deploy to MyGenies server dev

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: ["dev"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js 21
        uses: actions/setup-node@v3
        with:
          node-version: 21


      - name: Check build backend
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          cd backend
          npm install
          npm run build

      - name: Pull code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

          script: |
            cd /home/web/mygenies/dev
            export NVM_DIR="$HOME/.nvm"
            source ~/.nvm/nvm.sh
            nvm use 21
            git pull
            npm install -g pm2


      - name: Build backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

          
          script: |
            cd /home/web/mygenies/dev/backend
            export NVM_DIR="$HOME/.nvm"
            source ~/.nvm/nvm.sh
            nvm use 21
            npm install && npm run build
            

      - name: Start backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

          script: |
            cd /home/web/mygenies/dev/backend
            export NVM_DIR="$HOME/.nvm"
            source ~/.nvm/nvm.sh
            nvm use 21
            pm2 delete mygenies_backend_dev
            pm2 start "npm run start" --name=mygenies_backend_dev


      - name: Start python lab
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

          script: |
            cd /home/web/mygenies/dev/lab
            export NVM_DIR="$HOME/.nvm"
            source ~/.nvm/nvm.sh
            nvm use 21
            source .venv/bin/activate
            pip install -r requirements.txt
            sh run-dev.sh
    